services:
  frontend:
    image: frontend
    container_name: front
    build:
      context: ./Frontend
    ports:
      - "3000:3000"
    networks:
      - pong-network
    volumes:
      - front_volume:/usr/share/nginx/html

  backend:
    image: backend
    container_name: back
    build:
      context: ./Backend
    ports:
      - "8000:8000"
    networks:
      - pong-network
    volumes:
      - back_volume:/backend
    depends_on:
      - database
    env_file: .env

  game:
    image: game
    container_name: 1vs1-local
    build:
      context: ./Game
    ports:
      - "8080:80"
    networks:
      - pong-network
  
  database:
    image: postgres:13
    ports:
      - "5432:5432"
    networks:
      - pong-network
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    env_file: .env

networks:
  pong-network:
    driver: bridge

volumes:
  front_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./Frontend
  back_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./Backend/Pong
  postgres_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/Desktop/pres_database
