# Generated by Django 5.1.2 on 2024-11-04 02:24

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_profile_id_user_profile_is_online_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='default_pfp.jpg', upload_to='profile_images/', validators=[core.validators.validate_size]),
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Accepted'), ('P', 'Pending'), ('R', 'Rejected')], default='P', max_length=1)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friendships', to='core.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_friendships', to='core.profile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sender', 'receiver'), name='unique_friendship'), models.UniqueConstraint(fields=('receiver', 'sender'), name='unique_reverse_friendship'), models.CheckConstraint(condition=models.Q(('sender', models.F('receiver')), _negated=True), name='no_self_friendship')],
            },
        ),
    ]
