# Generated by Django 5.1.3 on 2024-11-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_friendship_unique_friendship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Tour_played',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='Tour_won',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
