# Generated by Django 5.1.3 on 2024-11-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_tour_played_profile_tour_played_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='xps',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
