# Generated by Django 5.1.3 on 2024-11-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ft_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
