# Generated by Django 5.1.5 on 2025-01-23 19:10

import core.helpers
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_profile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='default_pfp.jpg', upload_to=core.helpers.profileimg_path, validators=[core.validators.validate_size]),
        ),
    ]
