# Generated by Django 5.1.3 on 2024-11-08 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_tour_played_profile_tour_won'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Tour_played',
            new_name='tour_played',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Tour_won',
            new_name='tour_won',
        ),
    ]
