# Generated by Django 5.1.3 on 2024-11-10 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profile_xps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('won', models.BooleanField()),
                ('date_played', models.DateTimeField()),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='played_match', to='core.profile')),
            ],
        ),
    ]
