const  langData = ({
        en: {
                selectLanguage: "Select language",
                changePicture: "Change Picture",
                logout: "Logout",
                changeAccount: "Change Account<br />Informations",
                firstName: "First",
                lastName: "Last",
                username: "Username",
                email: "Email",
                update: "Update",
                changePassword: "Change Password",
                oldPassword: "Old Password",
                newPassword: "New Password", 
                matchesPlayed: "Matches Played",
                winningMatches: "Winning Matches",
                welcomeMessage: "Welcome,",
                loss_1: "Loss",
                win_2: "Win",
                yourRank: "Your Rank",
                totalPlayers: "Total Players",
                notcat:"Notifications",
                Acpbutton:"Accept",
                rejectbutton:"Reject",
                joined: "Joined",
                tournamentsPlayed: "Tournaments Played",
                tournamentsWon: "Tournaments Won",
                leaderboardPosition: "Leaderboard Position",
                currentFriends: "Current Friends",
                level: "Level ",
                playPong:"Play Pong Online on the #1 Site!",
                friendsList: "Friends List",
                matchHistory: "Match History",
                login: "Login",
                "welcome-back": "Welcome back!",
                password_login: "Password",
                "remember-me": "Remember me",
                "login-button": "Login",
                or: "Or",
                "sign-in-intra": "Sign in with intra",
                "dont-have-account": "Don’t have an account?",
                "signup-link": "Signup",
                "signup": "Signup",
                "signup-details": "Just some details to get you in ...",
                password_signup: "Password",
                "confirm-password": "Confirm password",
                "signup-button": "Signup",
                "already-registered": "Already registered?",
                "login-link": "Login",
                modeSelection: "Mode selection game",
                alreadyplaying: "you are already in a game",
                winner: "Congratulations!",
                classicGame: "Classic Game",
                singleGame: "1 Versus 1",
                tournament: "Tournament",
                playTournament: "Play a tournament",
                myProfile: "My Profile",
                challenge: "Challenge",
                pending: "Pending...",
                accept: "Accept",
                addFriend: "Add Friend",
                notRankedYet: "Not ranked yet",
                changefriend: "Challenge",
                totalGames: "Total Games",
                gamesToday: "Games Today",
                onlineNow: "Online Now",
                friendsTitle: "Wants to be your friend",
                login_link: "Login",
                login_error: "Invalid credentials",
                settings: "Settings",
                playNow: "Play Now",
                remote: "Remote",
                local: "Local",
                gameStart: "Game Start",
                winner: "Winner",
                loser: "Loser",
                rematch: "Rematch",
                backToHome: "Back to Home",
                anothergame: "You are already playing in another game",
                homeBack: "Back to Home",
                leaveGame: "Leave Game",
                gameSr:"Game Start",
                toBeDetermined: "To be Determined",
                champion: "Champion",
        },
        fr: {
                selectLanguage: "Choisissez une langue",
                changePicture: "Changer l'image",
                logout: "déconnecter",
                changeAccount: "Modifier les Informations<br/>du compte",
                update: "Mettre à jour",
                changePassword: "Changer le mot de passe",
                oldPassword: "Ancien mot de passe",
                newPassword: "Nouveau mot de passe",
                gameSettings: "Paramètres de jeu",
                change: "Changer",
                welcomeMessage: "Bienvenue,",
                level: "Niveau ",
                settings: "Paramètres",
                playNow: "Jouer",
                notifications: "Notifications",
                playPong: "Jouez Pong en ligne sur le site #1!",
                totalGames: "Total des jeux",
                gamesToday: "Jeux Aujourd'hui",
                onlineNow: "En ligne maintenant",
                matchesPlayed: "Matchs joués",
                winningMatches: "Matchs gagnants",
                loss_1: "Perte",
                win_2: "Gagner",
                yourRank: "Votre classement",
                totalPlayers: "Nombre total de joueurs",
                notcat: "Notifications",
                Acpbutton: "Accepter",
                rejectbutton: "Rejeter",
                joined: "Rejoint",
                tournamentsPlayed: "Tournois joués",
                tournamentsWon: "Tournois gagnés",
                leaderboardPosition: "Votre classement",
                currentFriends: "Amis actuels",
                friendsList: "Liste d'amis",
                matchesPlayed: "Matchs joués",
                winningMatches: "Matchs gagnés",
                matchHistory: "Historique des matchs",
                login: "Connexion",
                "welcome-back": "Bon retour!",
                username: "Nom d'utilisateur",
                password: "Mot de passe",
                "remember-me": "Se souvenir de moi",
                "login-button": "Se connecter",
                or: "Ou",
                "sign-in-intra": "Se connecter avec Intra",
                "dont-have-account": "Vous n'avez pas de compte?",
                "signup-link": "S'inscrire",
                signup: "Inscription",
                "signup-details": "Quelques détails pour vous inscrire...",
                username: "Nom d'utilisateur",
                email: "Email",
                password: "Mot de passe",
                "confirm-password": "Confirmer le mot de passe",
                "signup-button": "S'inscrire",
                "already-registered": "Déjà inscrit?",
                "login-link": "Se connecter",
                enter_email: "Entrez votre email",
                reset_password_button: "Réinitialiser le mot de passe",
                or_text: "Ou",
                sign_in_intra: "Se connecter avec intra",
                signup_prompt: "Pas de compte ?",
                signup_link: "Inscrivez-vous",
                modeSelection: "Sélection du mode de jeu",
                alreadyplaying: "you are already in a game",
                winner : "Félicitations!",
                classicGame: "Jeu classique",
                singleGame: "1 Contre 1",
                tournament: "Tournoi",
                playTournament: "Jouer un tournoi",
                myProfile: "Mon Profil",
                challenge: "Défi",
                pending: "En attente",
                accept: "Accepter",
                addFriend: "Ajouter",
                notRankedYet: "Pas encore classé",
                changefriend: "Défi",
                friendsTitle:"Veut être votre amie",
                password_login:"Mot de passe",
                password_signup: "Mot de passe",
                login_link: "Se connecter",
                login_error:"Identifiants invalides",
                remote: "À distance",
                local: "Local",
                gameStart: "Démarrage",
                winner: "Gagnant",
                loser: "Perdant",
                rematch: "Revanche",
                backToHome: "Retour à l'accueil",
                anothergame: "Vous jouez déjà dans une autre partie",
                homeBack: "Retour à l'accueil",
                leaveGame: "Quitter la partie",
                gameSr: "Démarrage",
                toBeDetermined: "À déterminer",
                champion: "Champion",
        },
        es: {
                selectLanguage: "Seleccionar idioma",
                changePicture: "Cambiar imagen",
                logout: "Cerrar sesión",
                changeAccount: "Cambiar cuenta<br />Información",
                firstName: "Nombre",
                lastName: "Apellido",
                username: "Nombre de usuario",
                email: "Correo electrónico",
                update: "Actualizar",
                changePassword: "Cambiar contraseña",
                oldPassword: "Contraseña antigua",
                newPassword: "Nueva contraseña",
                gameSettings: "Configuración del juego",
                change: "Cambiar",
                welcomeMessage: "Bienvenido,",
                level: "Nivel ",
                settings: "Configuración",
                playNow: "Jugar Ahora",
                notifications: "Notificaciones",
                playPong: "¡Juega Pong en línea en el sitio #1!",
                totalGames: "Juegos Totales",
                gamesToday: "Juegos de Hoy",
                onlineNow: "En línea Ahora",
                matchesPlayed: "Partidos Jugados",
                winningMatches: "Partidos Ganados",
                loss_1: "Pérdida",
                win_2: "Victoria",
                yourRank: "Tu Clasificación",
                totalPlayers: "Jugadores Totales",
                notcat: "Notificaciones",
                Acpbutton: "Aceptar",
                rejectbutton: "Rechazar",
                joined: "se unió",
                tournamentsPlayed: "Torneos jugados",
                tournamentsWon: "Torneos ganados",
                leaderboardPosition: "Posición en la tabla",
                currentFriends: "Amigos actuales",
                friendsList: "Lista de amigos",
                matchesPlayed: "Partidos jugados",
                winningMatches: "Partidos ganados",
                loss: "Derrota",
                win: "Victoria",
                matchHistory: "Historial de partidos",
                login: "Iniciar sesión",
                "welcome-back": "¡Bienvenido de nuevo!",
                username: "Nombre de usuario",
                password: "Contraseña",
                "remember-me": "Recuérdame",
                "login-button": "Iniciar sesión",
                or: "O",
                "sign-in-intra": "Iniciar sesión con Intra",
                "dont-have-account": "¿No tienes cuenta?",
                "signup-link": "Regístrate",
                signup: "Registrarse",
                "signup-button": "Registrarse",
                modeSelection: "Selección de modo de juego",
                alreadyplaying: "you are already in a game",
                winner : "¡Felicitaciones!",
                classicGame: "Juego clásico",
                singleGame: "1 Contra 1",
                tournament: "Torneo",
                playTournament: "Jugar un torneo",
                myProfile: "Mi Perfil",
                challenge: "Desafiar",
                pending: "Pendiente...",
                accept: "Aceptar",
                addFriend: "Agregar",
                notRankedYet: "No clasificado aún",
                changefriend: "Desafiar",
                friendsTitle:"Quiere ser tu amigoa",
                password_login: "Contraseña",
                "confirm-password": "Confirmar contraseña",
                password_signup: "Contraseña",
                "login-link": "Iniciar sesión",
                 "already-registered":"¿Ya estás registrado",
                 "signup-details":"Solo algunos detalles para que puedas entrar",
                login_error: "Credenciales inválidas",
                remote: "Remoto",
                local: "Local",
                gameStart: "Inicio del juego",
                winner: "Ganador",
                loser: "Perdedor",
                rematch: "Revancha",
                backToHome: "Volver al inicio",
                anothergame: "Ya estás jugando en otra partida",
                homeBack: "Volver al inicio",
                leaveGame: "Salir del juego",
                gameSr: "Inicio del juego",
                toBeDetermined: "Por determinar",
                champion: "Campeón",
        },
});

import {fetchProtectedUrl, alertMessage} from "./utils.js";

async function updateLanguageContent() {
        let currLang = localStorage.getItem('lang') || 'en';
        if (!['/', '/sign-up'].includes(window.location.pathname))
        {
                try {
                const response = await fetchProtectedUrl('/api/profiles/me/');
                if (!response.ok)
                        alertMessage('Failed to fetch profile.');
                
                const data = await response.json();
                currLang = data.language;
                localStorage.setItem('lang', currLang);
                } catch (error) {
                        alertMessage(error.message);
                }
        }

        const elements = document.querySelectorAll("[data-i18n]");
        elements.forEach((el) => {
                const key = el.getAttribute("data-i18n");
                
                if (key) 
                el.innerHTML = langData[currLang]?.[key] || key;
        });


        const placeholders = document.querySelectorAll("[data-i18n-placeholder]");
        placeholders.forEach((input) => {
                const key = input.getAttribute("data-i18n-placeholder");
                if (key)
                        input.placeholder = langData[currLang]?.[key] || key;
        });

        const buttons = document.querySelectorAll("[data-i18n-button]");
        buttons.forEach((btn) => {
                const key = btn.getAttribute("data-i18n-button");
                if (key)
                btn.textContent = langData[currLang]?.[key] || key;
        });
}
      
export default updateLanguageContent;

